In [2]:
# 列表转化成ndarray
import numpy as np
list = [1,2,3,4,5]
arr = np.array(list)
print(list,arr)
print(type(list),type(arr))

[1, 2, 3, 4, 5] [1 2 3 4 5]
<class 'list'> <class 'numpy.ndarray'>


# ndarray与python原生list的速度对比

In [3]:
import random
import time
# 随机取一亿个数
a = []
for i in range(10**8):
    a.append(random.randint(0,1000000))
print('取数完成')

取数完成


In [4]:
# 将list转化成ndarray
b = np.array(a)
print('转化完成')
# 计算两者的时间差
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

t3 = time.time()
sum2 = np.sum(b)
t4 = time.time()
print(t2-t1,t4-t3)

转化完成
2.072876214981079 0.039544105529785156


In [5]:
print(type(range(10)))  # range返回的是一个range对象，不能直接转换为ndarray
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [6]:
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray =np.array(list2)  # 二维列表转化成二维数组
print(type(twoArray))
print(twoArray)
print(list2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [8]:
twoArray.tolist()  # 二维数组转化成二维列表

[[1, 2], [3, 4], [5, 6]]

# 数组的各种属性

In [9]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像)
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype)  #默认int32,4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int32


# 调整数组的形状

In [10]:
four = np.array([[1,2,3],[4,5,6]])
print(four)

four1 = four
print(id(four1))


[[1 2 3]
 [4 5 6]]
1436661466288


In [11]:
four.shape = (3, 2)  # 改变形状,将shape看成ndarray的一个属性，id不会改变
print(id(four))
print(id(four1))
print(four)

1436661466288
1436661466288
[[1 2]
 [3 4]
 [5 6]]


In [12]:
print('-' * 50)
# 返回一个新的数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
four2

--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
1436661466288
1436661468400


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 将多维数组变成一维数组
five =four.reshape((6,),order='C')
# 默认情况下‘C’是按行优先，‘F’是按列优先
six =four.flatten() # 展开成一维数组
print(five,six)

[1 2 3 4 5 6] [1 2 3 4 5 6]


In [14]:
# 改变数组形状
seven = five.reshape((3,2))
print(seven)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
# 数组的形状
t = np.arange(24)  # arange返回的类型是ndarray
print(t)
print(f'shape{t.shape}')  # 输出形状
print(f'dim{t.ndim}')  # 输出维度
t1 = t.reshape(4,6)
print(t1)
print(f'shape{t1.shape}')  # 输出形状

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
dim1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
shape(4, 6)


In [16]:
#转换成三维
# 前面是0轴，轴越小，越靠外，最小的轴是最外层
t2 = t1.reshape(2,3,4)
print(t2)
print(f'shape{t2.shape}')  # 输出形状
print(f'dim{t2.ndim}')  # 输出维度

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape(2, 3, 4)
dim3


In [17]:
t3 = t1.reshape(2,3,2,2)
print(t3)
print(f'{t3.shape}')  # 输出形状
print(f'{t3.ndim}')  # 输出维度

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


In [18]:
# 将数组转换成列表形式
a = np.array([9, 12, 88, 14, 25])  # array是让数据变成数组
print(type(a))
list_a =a.tolist()  # list是python原生的数据类型
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


# numpy的数据类型

In [19]:
f = np.array([1,2,3,4,127],dtype = np.int8)
print(f.itemsize)  # itemsize是每个元素的字节数
print(f.dtype)

1
int8


In [20]:
f[4] += 1#超出数据范围会溢出
print(f[4])

-128


In [21]:
# 调整数据类型
f1 = f.astype(np.int64)  # astype是将数据类型转换成另一种类型
print(f1.dtype)
print(f1.itemsize)  #显示字节数
print('-' * 50)

int64
8
--------------------------------------------------


In [22]:
arr = np.array([random.random() for i in range(10)])  # 随机生成10个0-1之间的小数
print(arr)
print(arr.dtype)
print(np.round(arr,2))  # 保留两位小数输出

[0.52670877 0.39233391 0.48953294 0.14556136 0.64546379 0.78308244
 0.95666225 0.69999811 0.47504971 0.69613953]
float64
[0.53 0.39 0.49 0.15 0.65 0.78 0.96 0.7  0.48 0.7 ]


# 数组和数的计算

In [23]:
[1, 2, 3] + 5 # list列表不能加数

TypeError: can only concatenate list (not "int") to list

In [ ]:
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)
t2 = t1.tolist()
print(t1 + 2)
# print(t2+2) 不能对列表进行直接加整数操作
print("-" * 20)
print(t1 * 2)
print("-" * 20)
print(t1 / 2)

#无论多少维的ndarray都可以直接和一个常数进行运算

In [ ]:
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100,124).reshape(6,4)
print(t1,t2)
print("-" * 50)
print(t1 + t2)
print("-" * 50)
print(t1 * t2) # 并不是矩阵乘法，而是对应位置元素相乘

In [ ]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((3, 6))
print(t1)
print(t2)
print(t1 - t2)

In [ ]:
# 一维数组和二维数组进行运算时,一维的个数和列数相同
t1 = np.arange(24).reshape(4,6)
t2 = np.arange(6).reshape(1,6)
print(t2.shape)
print((t2-t1).shape)
t1 - t2

In [ ]:
#随机3维数组
# 结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1
# 只能有一个size不同，其他的轴的size必须要相同
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
a - b

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))
print("-" * 20)

In [ ]:
a = np.arange(24).reshape((2, 3, 4))
print(a)
b = np.sum(a, axis=0)  # 两个3 * 4的数组进行相加
print("-" * 20)
print(b.shape)
print(b)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)

# 索引和切片

In [ ]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开

In [ ]:
t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行

In [ ]:
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]

t1[1:3, 1:4]  #取1-3行，1-4列

# 修改值

In [24]:
t1 = np.arange(24).reshape(4,6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
t = t.clip(8,10)  # 小于8的修改为8，大于10的修改成10
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1436661523536
--------------------------------------------------
[ 8  8  8  8  8  8  8  8  8  9 10 10 10 10 10 10 10 10 10 10 10 10 10 10]


In [26]:
t = np.arange(24).reshape(4,6)
t < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [28]:
# python的三目运算
a = 10
b = 15
c =a if a > b else b
c

15

In [29]:
# 拓展三目运算，np.where(condition,x,y) 满足condition的输出x，不满足的输出y
score =np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score>80,True,False)
result

[[80 88]
 [82 81]
 [75 81]]


array([[False,  True],
       [ True,  True],
       [False,  True]])

In [30]:
score[result] = 10086
print(score)

[[   80 10086]
 [10086 10086]
 [   75 10086]]


# 数据添加删除与去重

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a,[7, 8, 9]))  #ndarray会被展平
print('\n')
print(a)
print('-' * 50)

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [32]:
print('沿轴 0 添加元素：')  #往哪个轴添加，那个轴size就变大
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print(a)
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print(a)
print('-' * 50)


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]
沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [33]:
# # 2. numpy.insert
# # 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# # 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。

a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 1, [11, 22]))  # 在dim=0的索引1处插入值
print('-' * 50)
print(np.insert(a, 1, [11, 12], axis=0))  #那个轴插入，哪个轴size变大
# print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴  0 广播：')
print(np.insert(a, 1, 11, axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, 1, [1, 2, 5], axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1 11 22  2  3  4  5  6]
--------------------------------------------------
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
沿轴  0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴  1 广播：
[[1 1 2]
 [3 2 4]
 [5 5 6]]


In [38]:
a = np.arange(12).reshape(3,4)
print('第一个数组')
print(a,'\n')

print('在未传递axis参数下，输入的数组将会被展开')
print(np.delete(a,2))  # 展平后删除索引为2的元素
print('-' * 50)
print('删除第一行')
print(np.delete(a,1,axis = 0))
print('删除第一列')
print(np.delete(a,1,axis = 1))

第一个数组
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

在未传递axis参数下，输入的数组将会被展开
[ 0  1  3  4  5  6  7  8  9 10 11]
--------------------------------------------------
删除第一行
[[ 0  1  2  3]
 [ 8  9 10 11]]
删除第一列
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [39]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展平
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

print('第一个数组：')
print(a)
print('\n')

#去除重复元素，输出的是有序序列
# print ('第一个数组的去重值：')
# u = np.unique(a)
# print (u)
# print ('\n')

# print ('去重数组的索引数组：')
# u,indices = np.unique(a, return_index = True)
# print(u)
# print (indices)
# print ('\n')

# print ('我们可以看到每个和原数组下标对应的数值：')
# print ('去重数组的下标：')
# u,indices = np.unique(a,return_inverse = True)
# print (u)
# print (indices)
# print ('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u)
print(indices)
u

第一个数组：
[5 2 6 2 7 5 6 9 8 2]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


array([2, 5, 6, 7, 8, 9])

# numpy的数学计算

In [40]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值，对应的轴就消失
result = np.max(score, axis=1)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)
# 5. 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；


'''通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''



[[80 88]
 [82 81]
 [75 81]]
88
[88 82 81]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 4 4 5]


'通用函数：\nnumpy.sqrt(array)\t平方根函数\nnumpy.exp(array)\te^array[i]的数组\nnumpy.abs/fabs(array)\t计算绝对值\nnumpy.square(array)\t计算各元素的平方 等于array\t2\nnumpy.log/log10/log2(array)\t计算各元素的各种对数\nnumpy.sign(array)\t计算各元素正负号\nnumpy.isnan(array)\t计算各元素是否为NaN\nnumpy.isinf(array)\t计算各元素是否为NaN\nnumpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数\nnumpy.modf(array)\t将array中值得整数和小数分离，作两个数组返回\nnumpy.ceil(array)\t向上取整,也就是取比这个数大的整数\nnumpy.floor(array)\t向下取整,也就是取比这个数小的整数\nnumpy.rint(array)\t四舍五入\nnumpy.trunc(array)\t向0取整\nnumpy.cos(array)\t正弦值\nnumpy.sin(array)\t余弦值\nnumpy.tan(array)\t正切值\n\nnumpy.add(array1,array2)\t元素级加法\nnumpy.subtract(array1,array2)\t元素级减法\nnumpy.multiply(array1,array2)\t元素级乘法\nnumpy.divide(array1,array2)\t元素级除法 array1./array2\nnumpy.power(array1,array2)\t元素级指数 array1.^array2\nnumpy.maximum/minimum(array1,aray2) 元素级最大值\nnumpy.fmax/fmin(array1,array2)\t元素级最大值，忽略NaN\nnumpy.mod(array1,array2)\t元素级求模\nnumpy.copysign(array1,array2)\t将第二个数组中值得符号复制给第一个数组中值\nnumpy.greater/greater_equal/less/less_equal/equa

In [41]:
# 6. 求平均值
result = np.mean(score)  # 获取所有数据的平均值
print(result)
result = np.mean(score, axis=0)  # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.cumsum(axis=0))
'''
[1, 2, 3]------>	|1	|2	|3	|
[4, 5, 6]------>	|5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(axis=1))
'''
[1, 2, 3]------>	|1	|2+1	|3+2+1	|
[4, 5, 6]------>	|4	|4+5	|4+5+6	|
'''



# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


'\n[1, 2, 3]------>\t|1\t|2+1\t|3+2+1\t|\n[4, 5, 6]------>\t|4\t|4+5\t|4+5+6\t|\n'

In [42]:
# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median
# 8. argmin求最小值索引
result = np.argmin(score, axis=0)
res = np.min(score, axis=0)  #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result, res)

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score, axis=0)
print(result)

# 10. 极 值
result = np.ptp(score, axis=None)  #就是最大值和最小值的差
print(result)

[2 1] [75 81]
[2.94392029 3.29983165]
13


In [44]:
t = np.arange(30).reshape(3,10)
print(t)
np.mean(t,axis = 0)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

# 数组的拼接

In [45]:
# 有的时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np

# 1. 根据轴连接的数组序列，concatenate没有改变数组的维度
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
# # 要求a,b两个数组的维度相同
print('沿轴 0 连接两个数组：')
print(np.concatenate((a, b), axis=0))  #写哪个轴，哪个轴就变化
print('-' * 50)

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------------------------------------


In [46]:
print('沿轴 1 连接两个数组：')
print(np.concatenate((a, b,c), axis=1))

沿轴 1 连接两个数组：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [48]:
print(np.concatenate((a, b, c), axis=1))
#堆叠
print('-' * 50)
print(np.stack((a, b, c), axis=1).shape)  #stack会增加维度
print(np.stack((a, b, c), axis=1))

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
--------------------------------------------------
(2, 3, 2)
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


# 数组的分割

In [ ]:
# 1. split函数，将数组按照指定轴进行分割，返回一个列表
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('沿轴 0 分割数组：')

In [50]:
# 2. 根据轴进行堆叠，2维会变为3维
arrays = [np.arange(12).reshape(3, 4) for _ in range(10)]
# print(arrays)
print(len(arrays))
print('沿轴 0 连接两个数组：')
result0 = np.stack(arrays, axis=0)
print(result0.shape)  #(10,3,4)
# print (result0)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
10
沿轴 0 连接两个数组：
(10, 3, 4)


In [51]:


# # # 3. 矩阵垂直拼接，vstack没有增加维数，类似于concatenate   ---vertical
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)

# # # 4. 矩阵水平拼接，类似于concatenate  horizontal
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.hstack((v1, v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


In [52]:
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
'''
import numpy as np

arr = np.arange(12).reshape(4, 3)
print(arr)
print('将数组分为三个大小相等的子数组：b是一个列表')
b = np.split(arr, 3, axis=1) #按那个轴，那个轴发生变化
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
将数组分为三个大小相等的子数组：b是一个列表
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [53]:
b = np.split(arr, 4, axis=0)  # 将arr切成四份
print(b)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [54]:
c = np.hsplit(arr, 3)  # 将arr竖着切成3分
print(c)  #c是列表
print(c[0].shape)

[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
(4, 1)


In [55]:
# # 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4, 4)

print('第一个数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# numpy inf和nan

In [57]:
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)  # np.nan不等于np.nan
print(True == 1)
print(False == 0)
np.nan + 1  #nan和其他数运算的结果都是nan

False
True
True


nan

In [58]:
# --判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [59]:
print(np.count_nonzero(t != t)) # 统计t中nan的个数

2


In [61]:
t[np.isnan(t)] = 0# 将t中的nan替换成0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [66]:
for i in range(t.shape[1]): # 遍历t的每一列
    temp_col = t[:,i]  # 取出t的第i列数据
    nan_num = np.count_nonzero(temp_col != temp_col)  # 当其中的某个元素与自生不相等是，那么该数就为nan
    if nan_num != 0:  # 说名这一列中有nan
        temp_col_not_nan = temp_col[temp_col == temp_col] # 取出不为 nan的数
        print(temp_col_not_nan)
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print(t)



[[ 0.          1.          2.          3.          4.          5.        ]
 [ 6.          7.          8.         13.          1.33333333 15.        ]
 [12.         13.         14.         15.          0.         17.        ]
 [18.         19.         20.         21.          0.         23.        ]]


In [67]:
print(np.inf == np.inf)# 无穷大是相同的

True


# 转置和轴运动

In [70]:
a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print('\n')
print('数组转置：')
print(np.transpose(a))
print(a)

# 与transpose一致
a = np.arange(12).reshape(3, 4)

print('原数组：')
print(a)
print('\n')

print('转置数组：')  # 与transpose一致
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


数组转置：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [71]:
#如果是3维及以上，称为轴交换
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)


In [75]:
# 数组的轴滚动,swapaxes每次智能交换两个轴,没有roolaxis方便,默认情况下是轴滚动最前面
a = np.ones((3,4,5,6))
b = np.rollaxis(a,3,1)
print(b.shape)

(3, 6, 4, 5)


In [81]:
print(b.shape)
c=np.moveaxis(b, 1,3)  #可以使用moveaxis进行轴的滚动,将1轴滚动到3轴的位置
print(c.shape)

(3, 6, 4, 5)
(3, 4, 5, 6)


In [83]:
names = 'Alice, Bob, Charlie'
# 写入文件
with open('names.csv','w') as f:
    f.write(names)
    f.write('\n')
    f.write('12,23,34')